# Generated by Django 4.1.6 on 2023-03-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="devolucion",
            fields=[
                (
                    "id_devoluciones",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nombrelibro", models.CharField(max_length=150)),
                ("fecha", models.DateField()),
                ("acta", models.CharField(max_length=150)),
                ("detalle", models.TextField()),
                ("nombre_da", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="incioseccion",
            fields=[
                ("idinicio", models.AutoField(primary_key=True, serialize=False)),
                ("usuario", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="inventario",
            fields=[
                ("id_inventario", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=150)),
                ("autor", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=150)),
                ("detalle", models.CharField(max_length=150)),
                ("cantidad_po", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=150)),
                ("cantidad", models.IntegerField()),
                ("nombrelibro", models.CharField(max_length=150)),
                ("actor", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="prestamo",
            fields=[
                ("id_prestamo", models.IntegerField(primary_key=True, serialize=False)),
                ("detalle", models.CharField(max_length=150)),
                ("nombrealumno", models.CharField(max_length=150)),
                ("actor", models.CharField(max_length=150)),
                ("fecha", models.DateField()),
                ("n_libro", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="registrousuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombrealumno", models.CharField(max_length=100)),
                ("apellidoP", models.CharField(max_length=50)),
                ("apellidoM", models.CharField(max_length=50)),
                ("correo", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=20)),
                ("edad", models.IntegerField(blank=True)),
                ("carrera", models.CharField(max_length=100)),
                ("genero", models.CharField(max_length=100)),
                ("usuario", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="responsablebibli",
            fields=[
                ("id_responsable", models.AutoField(primary_key=True, serialize=False)),
                ("nombreresponsable", models.CharField(max_length=100)),
            ],
        ),
    ]
