# Generated by Django 4.1.6 on 2023-06-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrousuario',
            name='apellidoM',
        ),
        migrations.RemoveField(
            model_name='registrousuario',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='registrousuario',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='registrousuario',
            name='password',
        ),
        migrations.RemoveField(
            model_name='registrousuario',
            name='usuario',
        ),
    ]
