# Generated by Django 4.1.6 on 2023-03-15 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="libro",
            options={"verbose_name": "Registro de Libros"},
        ),
        migrations.AlterModelOptions(
            name="registrousuario",
            options={"verbose_name": "Registro de usuarios"},
        ),
        migrations.AlterModelTable(
            name="libro",
            table="Libros",
        ),
        migrations.AlterModelTable(
            name="registrousuario",
            table="Registro_user",
        ),
    ]
