# Generated by Django 4.1.6 on 2023-02-14 05:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_devoluciones_inventario_libro_prestamo_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="devoluciones",
            new_name="devolucion",
        ),
    ]
