# Generated by Django 4.1.6 on 2023-03-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_libro_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrousuario",
            name="matricula",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
